@startuml packages_DataAcquisition
set namespaceSeparator none
package "src" as src {
}
package "src.acquire" as src.acquire {
}
package "src.csv_extract" as src.csv_extract {
}
package "src.model" as src.model {
}
src.acquire --> src.csv_extract
src.csv_extract --> src.model
@enduml
